esphome:
  name: smartspeakertest
  friendly_name: SmartSpeakerTest

rp2040:
  board: rpipicow

# Enable logging
logger:
  level: DEBUG
  baud_rate: 115200

# Enable Home Assistant API
api:
  encryption:
    key: "DOeS9hT2LDuLpxHXLw0Zlog9aGRDfj5ObHTolGy4kU4="

ota:
  - platform: esphome
    password: "aeac347f9c84c604ce4482d8fe71a3c0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  manual_ip:
    static_ip: 10.20.0.21
    gateway: 10.20.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Secretnetwork Fallback Hotspot"
    password: "QQtxKq9anw2h"
    