esphome:
  name: smartspeakeresp32
  friendly_name: SmartSpeakerESP32

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret smartspeaker_ha_key

ota:
  - platform: esphome
    password: !secret smartspeaker_ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smartspeakeresp32"
    password: "pagVEo7Gwzda"

captive_portal:
    